In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv ('water.txt', sep = '\t')

In [3]:
data.head()

location        town  mortality  hardness
0    South        Bath       1247       105
1    North  Birkenhead       1668        17
2    South  Birmingham       1466         5
3    North   Blackburn       1800        14
4    North   Blackpool       1609        18

In [4]:
data.shape

(61, 4)

In [7]:
correl1 = np.array (data[['mortality','hardness']].corr())

array([[ 1.        , -0.65484862],
       [-0.65484862,  1.        ]])

In [13]:
print round (correl1[1][0],4)

-0.6548


In [14]:
correl2 = np.array (data[['mortality','hardness']].corr(method = 'spearman'))

In [18]:
print round (correl2[1][0],4)

-0.6317


In [21]:
data_s = data[data['location'] == 'South']
data_n = data[data['location'] == 'North']

In [23]:
correl3 = np.array (data_s[['mortality','hardness']].corr())
correl4 = np.array (data_n[['mortality','hardness']].corr())

In [27]:
print round (correl3[1][0],4)
print round (correl4[1][0],4)

-0.6022
-0.3686


In [32]:
data2 = np.array([[515,239],[718,203]])

In [33]:
import math

In [34]:
corr_mathew = float(515*203 - 239*718)/math.sqrt ((515+239)*(515+718)*(239+203)*(718+203))

In [38]:
round (corr_mathew,3)

-0.109

In [39]:
import scipy.stats

In [41]:
scipy.stats.chi2_contingency (data2)

(19.40753078854304,
 1.0558987006638725e-05,
 1,
 array([[555.03402985, 198.96597015],
        [677.96597015, 243.03402985]]))

In [42]:
mans = np.array(0)
for i in range (0,754):
    if i <514:
        mans = np.append (mans,0)
    if i > 514:
        mans = np.append (mans,1)

In [45]:
womans = np.array(0)
for i in range (0,921):
    if i <717:
        womans = np.append (womans,0)
    if i > 717:
        womans = np.append (womans,1)

In [58]:
l = np.array ([0]*718+[1]*203)

In [63]:
def proportions_confint_diff_ind(sample1, sample2, alpha = 0.05):    
    z = scipy.stats.norm.ppf(1 - alpha / 2.)   
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    left_boundary = (p1 - p2) - z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    right_boundary = (p1 - p2) + z * np.sqrt(p1 * (1 - p1)/ len(sample1) + p2 * (1 - p2)/ len(sample2))
    
    return (left_boundary, right_boundary)

In [95]:
d_b,u_b = proportions_confint_diff_ind(mans,womans)
print d_b,u_b

0.053905233215813156 0.13922183141523897


In [96]:
round (d_b,4)

0.0539

In [68]:
def proportions_diff_z_test(z_stat, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    if alternative == 'two-sided':
        return 2 * (1 - scipy.stats.norm.cdf(np.abs(z_stat)))
    
    if alternative == 'less':
        return scipy.stats.norm.cdf(z_stat)

    if alternative == 'greater':
        return 1 - scipy.stats.norm.cdf(z_stat)

In [69]:
def proportions_diff_z_stat_ind(sample1, sample2):
    n1 = len(sample1)
    n2 = len(sample2)
    
    p1 = float(sum(sample1)) / n1
    p2 = float(sum(sample2)) / n2 
    P = float(p1*n1 + p2*n2) / (n1 + n2)
    
    return (p1 - p2) / np.sqrt(P * (1 - P) * (1. / n1 + 1. / n2))

In [70]:
proportions_diff_z_test (proportions_diff_z_stat_ind(womans,mans))

8.153453089576601e-06

In [71]:
import statsmodels.stats.proportion

In [78]:
data3 = np.array ([[197,111,33],[382,685,331],[110,342,333]])

In [81]:
dt = pd.DataFrame (data3)

In [94]:
scipy.stats.chi2_contingency (data3)

(293.68311039689746,
 2.4964299580093467e-62,
 4,
 array([[ 93.08597464, 153.74722662,  94.16679873],
        [381.6251981 , 630.318542  , 386.0562599 ],
        [214.28882726, 353.93423138, 216.77694136]]))

In [88]:
chi = scipy.stats.chi2_contingency (data3)[0]

In [90]:
print round (chi,4)

293.6831


In [101]:
v_kramer = math.sqrt(chi/(sum(data3.reshape(9))*2))

In [102]:
round (v_kramer,4)

0.2412