In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv ('AUCs.txt', sep = '\t')

In [4]:
data.head()

Unnamed: 0   C4.5  C4.5+m  C4.5+cf  C4.5+m+cf
0           adult (sample)  0.763   0.768    0.771      0.798
1            breast cancer  0.599   0.591    0.590      0.569
2  breast cancer wisconsin  0.954   0.971    0.968      0.967
3                      cmc  0.628   0.661    0.654      0.657
4               ionosphere  0.882   0.888    0.886      0.898

In [6]:
data.shape

(14, 5)

In [7]:
import scipy.stats

In [9]:
scipy.stats.wilcoxon(data['C4.5'], data['C4.5+m'])

WilcoxonResult(statistic=6.5, pvalue=0.01075713311978963)

In [10]:
d_45 = np.array (data['C4.5'])

In [36]:
data.iloc [:,4]

0     0.798
1     0.569
2     0.967
3     0.657
4     0.898
5     0.931
6     0.685
7     0.625
8     0.875
9     1.000
10    0.962
11    0.669
12    0.975
13    0.970
Name: C4.5+m+cf, dtype: float64

In [32]:
for i in range (1,5):
    if i == 1:
        data_np = np.array (data.iloc[:,i])
    else:
        data_np = np.append (data_np, np.array ([data.iloc[:,i]]))

In [41]:
data_np = data_np.reshape (4,14)
print data_np[0]

[0.763 0.599 0.954 0.628 0.882 0.936 0.661 0.583 0.775 1.    0.94  0.619
 0.972 0.957]


[5]


In [59]:
p_v_arr = []
for i in range (len(data_np)-1):
    for j in range (i+1,len(data_np)):
        print i,j
        wilc_cr = scipy.stats.wilcoxon(data_np[i], data_np[j])[1]
        p_v_arr.append (wilc_cr)
        print wilc_cr

0 1
0.01075713311978963
0 2
0.861262330095348
0 3
0.015906444101703374
1 2
0.046332729793395394
1 3
0.3278256758446406
2 3
0.022909099354356588


In [70]:
for i in p_v_arr:
    if i <0.05:
        print i

0.01075713311978963
0.015906444101703374
0.046332729793395394
0.022909099354356588


In [71]:
p_v_arr

[0.01075713311978963,
 0.861262330095348,
 0.015906444101703374,
 0.046332729793395394,
 0.3278256758446406,
 0.022909099354356588]

In [65]:
import statsmodels.sandbox.stats.multicomp

# Поправка методом Холма

In [73]:
statsmodels.sandbox.stats.multicomp.multipletests (p_v_arr, alpha = 0.05, method = 'holm')

(array([False, False, False, False, False, False]),
 array([0.0645428 , 0.86126233, 0.07953222, 0.13899819, 0.65565135,
        0.0916364 ]),
 0.008512444610847103,
 0.008333333333333333)

# Поправка методом Бенджамини-Хохберта

In [75]:
statsmodels.sandbox.stats.multicomp.multipletests (p_v_arr, alpha = 0.05, method = 'fdr_bh')

(array([ True, False,  True, False, False,  True]),
 array([0.0458182 , 0.86126233, 0.0458182 , 0.06949909, 0.39339081,
        0.0458182 ]),
 0.008512444610847103,
 0.008333333333333333)